# Generated by Django 5.1.2 on 2024-11-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_study_study_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='study_description',
            field=models.TextField(),
        ),
    ]
